name: Self-hosted test
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [nodejs]
#    permissions:
#      contents: read
#      actions: read
#      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Compilation
#        run: find . -name "*.js" -exec node --check {} +

      - name: Run gitleaks scan
        run: gitleaks detect --source . --exit-code 1 --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif