name: Self-hosted test
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [nodejs]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks scan
        run: |
          ls
          gitleaks detect --source . --exit-code 1