name: Self-hosted test
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [nodejs]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compilation
        run: find . -name "*.js" -exec node --check {} +

      - name: Run gitleaks scan
        run: gitleaks detect --source . --exit-code 1

